### ISSUE TITLE
Remove margin from last item of nav lists

### ISSUE THREAD

**Issue by ethan-ou** [igoradamenko/awsm.css#101]
I was using a couple of lists in some header and footer navigations and I realised that margin was being added to the last element. This meant lists in the footer needed additional CSS to be centered.

![m8iRs1vBN9](https://user-images.githubusercontent.com/45083970/92449665-b7bf2a00-f1fd-11ea-8914-cfc38fab6c5b.png)

Was wondering if this was an intentional decision and that I should continue hacking around it with `nav li:last-child`.

Loving this project by the way!

**Comment by igoradamenko** [comment]
Hey!

I guess it's just a bug. I think we may remove `nav li:last-child`'s `margin-right` safely.

If you have a spare time, PR is welcome. Otherwise I will fix it this week.
