### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by alexspark** [igoradamenko/awsm.css#103]
I'd like to use pearl-lusta theme by default, but if the device has dark mode enabled, I'd like to use big-stone theme. Do you know how I can easily configure that?

**Comment by igoradamenko** [comment]
It depends on the tools you prefer to use.

If you're fine with JS solution, it may be probably something like this: 

```js
const DARK_THEME_MQ = '(prefers-color-scheme: dark)';

updateTheme();

function updateTheme() {
  if (window.matchMedia && window.matchMedia(DARK_THEME_MQ).matches) {
    // set <link>'s tag href to big-stone theme file
  } else {
    // set <link>'s tag href to pearl-lusta theme file
  }
}

window.matchMedia(DARK_THEME_MQ).addEventListener('change', updateTheme);
```

But if you prefer CSS over JS, then:

1. Create SCSS file like this:

    ```scss
    /* pearl-lusta css */
    
    @media (prefers-color-scheme: dark) {
      /* big-stone css */
    }
    ```

2. Transpile it to CSS using any SCSS transpiler, such as [sass](https://github.com/sass/dart-sass) or even online using [Sass Meister](https://www.sassmeister.com/).

3. Minify the result if you need to.

**Comment by alexspark** [comment]
I was hoping i wouldn't have to bulk copy paste all of the css from both themes. are the themes so custom that I can't just switch out the theme color variables in sass?

**Comment by igoradamenko** [comment]
Well, you can, but what next? You need to write media query for matching user's theme, and this query should have rules inside. You have to specify the rules. The fastest way to do it is just put there the whole theme and let the minifier do its job.

Themes are not so different when we're talking about the colors, but such colors are used everywhere. Do you want to get the minimal set of rules to override, or what?

I don't know what ways you prefer, what setup you use and so on. Can you describe the desired solution, please?

**Comment by cawlin** [comment]
@alexspark Here is a very simple way to achieve what you want. I am using this in my own site.

```
<link rel="stylesheet" href="https://unpkg.com/awsm.css/dist/awsm_theme_big-stone.min.css" media="(prefers-color-scheme: dark)">
<link rel="stylesheet" href="https://unpkg.com/awsm.css/dist/awsm_theme_pearl-lusta.min.css" media="(prefers-color-scheme: no-preference), (prefers-color-scheme: light)">
```

**Comment by igoradamenko** [comment]
@cawlin, neat!

I've added your solution to the README:

https://github.com/igoradamenko/awsm.css#dark-mode-support

And to the site:

https://igoradamenko.github.io/awsm.css/download.html#dark-mode

Thanks!
