### ISSUE TITLE
Enable/disable toggle on Elements page does not work on Firefox

### ISSUE THREAD

**Issue by pbx** [igoradamenko/awsm.css#106]
In Firefox 82.0 (64-bit) on Linux, viewing [demo site](https://igoradamenko.github.io/awsm.css/elements.html) which is running v3.0.7 as of this writing, the [toggleToggler](https://github.com/igoradamenko/awsm.css/blob/master/docs/elements.html#L337) function does not work as intended. 

The button shows up, but styles remain in effect.

No errors in JS console.

Feature works in current Chrome/Chromium on the same machine.

p.s. Very cool project!

**Comment by igoradamenko** [comment]
Hi Paul!

It looks like it does not work properly in any browser when the custom theme is chosen.

Thanks for the bug report, I will fix it soon 🐨

**Comment by igoradamenko** [comment]
@pbx, please, check it now. It should work fine.

(But be aware of cache.)

**Comment by igoradamenko** [comment]
Hope it works :-)
