### ISSUE TITLE
Idea: Visualize description of repo purpose

### ISSUE THREAD

**Issue by eko24** [igoradamenko/awsm.css#80]
It'll be easier to understand what your code do with "Before & After" image like this:![image](https://cloud.githubusercontent.com/assets/758017/21803668/c1683a4e-d733-11e6-9e4b-ab95d6a45f52.png)
-------
Also you could highlight that both images use same html code but second one (which is "After") have `awsm.css` stylesheet

Nice repo and idea though 👍

**Comment by igoradamenko** [comment]
@eko24, sounds cool! I will think about it and will try to create demo, thanks!

**Comment by rjk40** [comment]
Very nice kitty. Lol

**Comment by igoradamenko** [comment]
Hey!

I've added stylesheet toggler on the demo page. [Check this out](https://igoradamenko.github.io/awsm.css/elements.html#moar).

Closed by 932bc13.

**Comment by eko24** [comment]
@igoradamenko that's awesome !
