### ISSUE TITLE
H6 font-size smaller than paragraph text

### ISSUE THREAD

**Issue by zoxon** [igoradamenko/awsm.css#81]
![2017-01-11_15-28-26](https://cloud.githubusercontent.com/assets/3866196/21842877/d8a3f9c0-d812-11e6-840c-d5b57ed13558.png)

**Comment by igoradamenko** [comment]
Yep. There is no custom style for h6 font-size. I'm not sure that h4-h6 are useful in real life. But if you think so, I can add `font-size: 1em` and some colors for them. What do you say?

**Comment by zoxon** [comment]
IMHO you need add styles for h6 because h6 still in HTML specification and someone can use this

**Comment by neuotq** [comment]
h4-h6 font-size sometimes useful, but such cases has no common specs. So I think there is no need to have universal aproach. If someone want h6 in specific style, they can add own css for their project.

**Comment by rjk40** [comment]
Yes leave the option in users hand in the setting of the application agreed. Commit to the tree and make this a marked improvement. Thanks neuotq

**Comment by igoradamenko** [comment]
Fixed in 8861085c586c906f5aca24778ec67a80396afa11. It'll be released in v2.1.

<img width="703" alt="screen shot 2017-01-14 at 13 01 11" src="https://cloud.githubusercontent.com/assets/6537798/21954122/c3bd91f8-da59-11e6-9cd7-7189b9f4600b.png">
