### ISSUE TITLE
Form elements

### ISSUE THREAD

**Issue by calvintychan** [igoradamenko/awsm.css#82]
Nice repo and idea, @igoradamenko!
Any plan on supporting the basic form elements here?

**Comment by igoradamenko** [comment]
Hi @calvintychan!

Form elements were removed in the v2.0. If you want to get them, check the v1.2: https://github.com/igoradamenko/awsm.css/releases

I'm not sure that all form elements will be supported in the nearest future. Maybe only inputs / textareas will.

I want to release v2.1 at the weekend, and v2.2 in January. Next it would be great to create simple theme for Wordpress / Jekyll / any else blog engine or static site generator. And form elements may be need for them.

So, when I will be sure that they are needed — I will add them. Right now I'm not completely sure.

Roadmap (do not take it seriously, I'm not sure about these features):

v2.1:
- anchors for section headers (like in GitHub markdown);
- guide ”How to contribute”;
- demo improvement (#80) + more examples;
- styles for h4-h6 (#81).

v2.2:
- custom themes;
- options for postcss plugin for custom themes;
- visual testing with gemini (https://github.com/gemini-testing/gemini).

Hope it helps. Stay tuned!

**Comment by calvintychan** [comment]
Yeah, I don't think it needs to support all the form elements.  I was thinking the basic one such as input, select, textarea, and more importantly, buttons :) 

Looking forward to seeing the custom themes in v2.2!
