### ISSUE TITLE
Unnecessarily loading PT Sans font?

### ISSUE THREAD

**Issue by jordanlev** [igoradamenko/awsm.css#84]
The "PT Sans" font gets loaded, but it is only used in the css in one somewhat obscure place (`article header p`) -- which isn't even documented or used in your sample site. Perhaps it would be better to improve performance slightly by taking PT Sans out of the google font stylesheet link? Or was this a mistake and it should be used for more prominent tags like h1/h2/h3?

Thanks, this is a great project!

**Comment by igoradamenko** [comment]
Hello!

“PT Sans” is used in article's header info, yep. Check [this demo](https://igoradamenko.github.io/awsm.css/examples/blog/), look at the date of articles. It is not a mistake. 

Yes, maybe it would be better to remove “PT Sans” completely, but right now I'm not sure (I can't find such beautiful web-safe font). In the next release I will think about it. 

Thanks for your care!

**Comment by igoradamenko** [comment]
I'll close the issue when it will be done.
