### ISSUE TITLE
Meta Data for Social Networks 

### ISSUE THREAD

**Issue by dudeonthehorse** [igoradamenko/awsm.css#85]
Привет. Спасибо за твое решение. При помощи этой штуки на одном проекте по недвижке успешно запилили генератор html to pdf для распечатки инфы по объектам. Приятно пользоваться.

В качестве реквеста предлагаю запилить соответствующие мета-теги для социальных сетей, так как при шаринг страницы сейчас в мета-данных показывается ```<link rel="stylesheet">```

**Comment by igoradamenko** [comment]
Привет!

Спасибо за отзыв и за идею! Возьму на заметку и добавлю мета-данные в ближайшее время 🐨

**Comment by igoradamenko** [comment]
Ишью оставлю открытой, чтобы не забыть :)
