### ISSUE TITLE
Font styling and some elements

### ISSUE THREAD

**Issue by dudeonthehorse** [igoradamenko/awsm.css#86]
Также я брал за основу твой шаблон для своего фреймворка для сборки email рассылок https://github.com/dudeonthehorse/kilogram

Главная проблема PT sans - он прекрасен для текстовых и табличных данных, но вот кнопки с ним получаются достаточно унылыми

В итоге я остановился на более хитром семействе стоковых шрифтов:
```font-family: '-apple-system', helvetica, arial, sans serif```
Что дает условную нативность на каждой из возможных платформ при использовании беззасечковых шрифтов.

Получился вот такой вариант:
- https://yadi.sk/d/CbQwoMgW3DDcmG
- https://yadi.sk/d/r61RlO9n3DDccd

Что также хотелось бы видеть в твоей реализации:
- CSS Grid (25%, 33%, 50%, 66%, 75%). Хотя грид можно подглядеть и здесь https://github.com/dudeonthehorse/milligram
- Для грида можно использовать полифилы из https://github.com/zurb/inky
- Кнопки: полноцветная, прозрачная с рамкой, прозрачная без рамки
- Более богатый инструментарий таблиц для составления инвойсов (взять хотя бы https://www.getharvest.com/resources/invoice-template-pdf для примера)

**Comment by igoradamenko** [comment]
Гридов скорее всего не будет. Фишка библиотеки в том, что тут нет никаких классов и пр. Какой элемент может отвечать за гриды в HTML мне не совсем понятно. Предполагаю, что никакой.

Кнопки скорее всего будут. Вряд ли они будут разного цвета, потому что, опять же, HTML only. За шрифты спасибо, да. Возможно так и сделаю. От PT Sans скорее всего вообще откажусь, потому что в библиотеке он используется только в одном месте, и из-за этого как-то дорого тащить целый шрифт.

В сторону таблиц подумаю, возможно, накидаю какой-нибудь подобный макет, допишу стили, но ничего не обещаю.

Всё же библиотека в первую очередь про HTML без классов, айдишников, атрибутов и прочего-прочего :koala:

**Comment by igoradamenko** [comment]
А есть где-то в онлайне то, что на этом скрине https://yadi.sk/d/r61RlO9n3DDccd? Я могу добавить в раздел `Examples` в описание библиотеки, как пример сайта, построенного на основе awsm.

**Comment by dudeonthehorse** [comment]
А том то и дело, что это не сайт, а email шаблон. И в dev версии он все еще чистый, но после сборки становится весьма громоздким и замешанным на классах https://gist.github.com/dudeonthehorse/bba7693def10c11d0830a89eb44c153b

Я в этом месяце сделаю апдейт, на случай если интересно будет посмотреть результат, но пока что как минимум не стоит упоминания. А от awsm я постарался взять общую просьбу стилистику. Семантика все равно очень сильно отличается.

**Comment by igoradamenko** [comment]
Окей, понял :koala:

**Comment by igoradamenko** [comment]
Добавил системные шрифты вместо PT Sans в ba790c41126e5304a2e44627995079e37e36d78f.

Строчка в `font-family` получилась побольше, но суть та же.
