### ISSUE TITLE
WordPress theme: anatta

### ISSUE THREAD

**Issue by strauhmanis** [igoradamenko/awsm.css#90]
Hi!

This is a suggestion to add the WordPress theme "anatta" that uses awsm.css to the list of examples:
https://github.com/Rahmon/anatta

Thanks

**Comment by igoradamenko** [comment]
Hey @strauhmanis!

Thank you for your suggestion, but do you have any link to demo? I've only found the screenshot: https://github.com/Rahmon/anatta/blob/master/screenshot.png. It's okay, I can use it, but may be your theme has a demo page?

**Comment by strauhmanis** [comment]
I'm not affiliated with the creator of the WP theme. But if I will end up using the theme on any of my projects I will let you know about a live example.

**Comment by igoradamenko** [comment]
Oh, right!

Okay, thank you again, I will add link to the repo. Feel free to create new issue if you will want to add your project as a demo.
