### ISSUE TITLE
Работа стилей относительно родителя

### ISSUE THREAD

**Issue by avlysenko** [igoradamenko/awsm.css#92]
Игорь, привет!

Отличная библиотека, после использования которой очень быстро просыпается аппетит.

В текущей реализации стили начинаются от корня документа. Хотелось бы иметь возможность использовать ее для указанного контейнера.

Какие могут быть варианты реализации такой задачи?

- Руками убрать ссылки
- Использовать ПостЦСС для автоматической замены, при получении обновлений
- Сделать альтернативную версию библиотеки, чтобы не было привязки к корню документа

Руками быстро, но необходимо делать при каждому обновлении.

ПостЦСС правильно, но усложняет комбайн.

Альтернативная версия выглядит самым клевым решением. 

Надеюсь, когда-нибудь звезды сойдутся и она появится.

**Comment by igoradamenko** [comment]
@avlysenko, hey. I'm working right now on v3 of the lib, and want to fix this issue.

Tell me, please, what do you mean when you say 'alternative version'? Main styles, such as font-size, light-height, color, background, etc. are set inside 'html' and 'body' selectors. If we talk about alternative version, where should these styles be placed?

For me it looks like you need to wrap library inside some selector in this case. And if you can do it, usually you have building system and you can use postcsss.

If you have other ideas, please, share them :-)

**Comment by avlysenko** [comment]
Игорь, привет!

Попробуй привести пример, возможно, будет понятно о чем хотел сказать.

Мы разработали веб-ориентированную платформу, которая позволяет создавать и выгружать на сайт подготовленный контент,
https://www.lisenko.ru/store/almanac/

В момент редактирования, в окно предварительного просмотра можно подключить внещний css файл, чтобы в Альманахе можно были видеть шрифт и стили, которые будут использоваться на конечном сайте.

Так выглядит редактор,
http://images.stage.lisenko.ru/2018/ms/kmexgsk0tgdumwn.jpg

Так этот материал выглядит в Альманахе,
http://images.stage.lisenko.ru/2018/ms/f9f20br4g7etfid.jpg

Этот материал в Альманахе выводится внутри дива, поэтому если применять к нему стили, стили должны применяться относительно контейнера в котором находится созданный материал.

Твоя версия прикрепляет стили ко всей странице. 

А мне бы хотелось, чтобы эти прекрасные стили можно были прикрепить только для внутренних элементов заданного контейнера.

У меня получилось переформулировать задачу?

**Comment by igoradamenko** [comment]
Kind of.

I understand the task, I don't understand the solution :-)

Let's use pseudocode to describe the situation. You have something like this:

```html
<html>
  <head><!-- ... --></head>
  <body>
    <!-- ... -->
    <div id="content">
      <!-- content that you want to style using awsm -->
    </div>
    <!-- ... -->
  </body>
</html>
```

And you have awsm.css that contains styles like these:

```css
html { /* ... */ }
body { /* ... */ }
```

But you want to have styles like these:

```css
#content { /* ... */ }
#content { /* ... */ }
```

Right?

I can build a selector-based version, but it would be strange, wouldn't it? I mean, let's say that I can build custom version that uses `.awsm` as a root, and all selectors are contained inside `.awsm.css`, like this:

```css
.awsm { /* ... */ } /* instead of `html` and `body` */
.awsm p { /* ... */ } /* instead of `p` */
```

How will you use it? You say that you can attach some external CSS file inside some container, but that container is predefined by your content system, no? Or does this CMS allow you to add some classes to the content root? If it possible to add `.awsm` class there?

**Comment by avlysenko** [comment]
Этот вариант в моей голове.

`#content { /* ... */ }`

`.content { /* ... */ }`

Почему так?

В самом редакторе используется Маркдаун, поэтому он генерирует чистые теги без классов. 

Внешний CSS файл должен прописывать стили для заданного контейнера .content или #content. Он подключается в самом начале страницы. И если не указать контейнер, то он перезапишет стили самого Альманаха. Почему? Потому что для вывода предпросмотра не используется iframe.

Если возможно, так тоже было бы здорово:

`<div class="content awsm">`

**Comment by igoradamenko** [comment]
@avlysenko, check, please, is it what you want to get?

https://github.com/igoradamenko/awsm.css/blob/v3/dist/awsm_sealed.css

**Comment by igoradamenko** [comment]
I think that I released this feature in v3.0.0.

Check the doc: https://igoradamenko.github.io/awsm.css/download.html#sealed

Closing the issue now, but if I'm wrong feel free to reopen it.
