### ISSUE TITLE
Пропадает подчеркивание, если текст ссылки разбивается на две строки

### ISSUE THREAD

**Issue by avlysenko** [igoradamenko/awsm.css#93]
Если текст ссылки длинный и переносится на новую строку, то пропадает подчеркивание ссылки, при этом при наведении ссылка появляется.

macOS, 10.13.2
Safari, 11.0.2

**Comment by igoradamenko** [comment]
I think that was because links had borders.

In v3 they don't have them, so it works fine now:

![image](https://user-images.githubusercontent.com/6537798/51697048-94873d00-200f-11e9-89e7-332a77516585.png)

macOS 10.13.6, Safari 12.0.2.
