### ISSUE TITLE
Defect in select

### ISSUE THREAD

**Issue by dartess** [igoradamenko/awsm.css#95]
duplication of arrows:

![img](https://i.gyazo.com/e1ed34fefd03293adec0840a13c079cc.png)

![img](https://i.gyazo.com/222995bbca9493e1a2db1139221bea5b.png)

macOS 10.15.3 (19D76)
Chrome 80.0.3987.132

**Comment by igoradamenko** [comment]
It looks like `appearance: button` has been changed in the latest Chrome updates. `none` should be fine, I guess.

I will fix it somewhen, thanks. (But PR is always welcome.)
