### ISSUE TITLE
provision for 1 class name, hear me out ! [enhancement]

### ISSUE THREAD

**Issue by therealadityashankar** [igoradamenko/awsm.css#96]
An excellent use case for this library is for markdown-rendered pages, which is something you use if for too, however, I only want to style a certain section of my site styled with awsm.css (the markdown rendered section), everything else, I wanna style without awsm.css, using some custom css

I've tried the alternative of loading markdown-only content in iframes and then loading it on my site, and iframes have alot of styling related issues, and its really not good tbh.

moreover, I wasn't able to find a suitable library that actually does the work of styling everything underneath a div element with something like a "markdown-rendered-content" class, so that would actually be pretty neat.

Thanks in advance for considering this !

**Comment by igoradamenko** [comment]
Not sure that I understand your pain properly, but awsm has “sealed” version out of the box. E.g. each theme has sealed version:

https://igoradamenko.github.io/awsm.css/css/awsm_theme_white.css
https://igoradamenko.github.io/awsm.css/css/awsm_theme_white._sealed.css

Also PostCSS plugin API has `sealed` flag which enables the same thing but inside PostCSS:

https://igoradamenko.github.io/awsm.css/download.html#options

Anyway, when you use sealed version of the library, you can use `.awsm` class on nodes to style them awsm-ly.

Does it solve the problem?

**Comment by therealadityashankar** [comment]
yeah It does, Thanks for the support !
