### ISSUE TITLE
Support prefers-color-scheme out of box

### ISSUE THREAD

**Issue by constptr** [igoradamenko/awsm.css#97]
[Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

[Web.dev docs](https://web.dev/prefers-color-scheme/) 

CSS has special feature to set css properties of website automatically detecting OS/Browser's color-scheme.

I have noted that you have 8 color themes. It would be greatful if you create new automatic theme with white theme for light mode and black theme for dark mode which uses prefers color scheme . Those themes should make website white if browser is in light mode and black if browser is in dark mode.

**Comment by varsbhat** [comment]
In short, you do provide themes. But,i am asking to also provide auto-dark mode themes along with existing themes.

**Comment by igoradamenko** [comment]
I believe the decision like this may push the number of themes to infinity.

Let's suppose we create one auto-theme which switches between `white` and `black` themes. Should we also create another one which switches between `pastel-pink` and `gondola`? What about `tasman` and `big-stone`? Moreover, should we create sealed version for each of them? 

Today we have 8 themes, each of them goes in two variants: https://igoradamenko.github.io/awsm.css/download.html. If we decide to create auto-themes from each of them which can be probably paired (there are 5 “light” and 3 “dark” themes) we will get at least 15 new themes.

I really don't think it's a good idea. I think it's easier to do on the user's side with JS like this:

```js
if (window.matchMedia('(prefers-color-scheme: dark)')) {
  // change path to linked CSS file
}
```

**Comment by constptr** [comment]
Can atleast the 'Black' and 'white' theme be combined to form 'one' 'autotheme' ? I also think that js must not be used too

**Comment by Dorson** [comment]
The CSS rule for **@media screen and (prefers-color-scheme: dark) { }**  would work, but it would enforce one color only, and for the users that have that rule ON already. No way to switch it ON, OFF. Or give it to all as an option. 

To resolve that I did the hard work.

Made and tested the code for a CSS color switch with memory. Great for the night and evening time.

See live demo on GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to fork, copy, adopt, port, etc...
